#!/usr/bin/env bash

# Check if the first argument is empty
if [ -z "$1" ]; then
  echo "Please enter the bucket name eg: ./create-bucket my-bucket"
  exit 1
fi

# Assign the first argument to BUCKET_NAME
BUCKET_NAME=$1

# Create S3 bucket using AWS CLI
aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1